[google]
client_secrets = """
{
  "installed": {
    "client_id": "886946559653-dtefaphi635r219jc52lul9g42i2q03s.apps.googleusercontent.com",
    "project_id": "acc559",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_secret": "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",
    "redirect_uris": [
      "urn:ietf:wg:oauth:2.0:oob",
      "http://localhost"
    ]
  }
}
"""
